Drives list and Rides list
MOTIS-Mitfahr-App/flutter-app pull request #20
Opened 2022-12-07 11:04 UTC by istzen

add new Model trip. Both Ride and Drive extend trip. 
add generic list view and implement for Rides and Drives
add cards for drives, rides but their concrete design is part of another PR
move create drive form back into create_drive_page.

2022-12-07 11:30 UTC, Showcas approved these changes

2022-12-07 16:55 UTC, fynsta commented
I'm wondering if the dates should be part of the cards, or if there should be a labeled separator for each day

2022-12-07 16:56 UTC, fynsta commented
I definitely like the nice generalization 👍

2022-12-07 17:42 UTC, Eddie-42 commented
> I definitely like the nice generalization 👍

I second that!

2022-12-07 20:21 UTC, istzen commented
> I'm wondering if the dates should be part of the cards, or if there should be a labeled separator for each day
> 

I thought about that too, but then again especially for the rides, i don't think their will be more than one or two cards per user, so i think having the date with the cards is not a problem. Also it might look weird when there is one Card an a Date above it.

2022-12-07 20:24 UTC, istzen commented
> 
> I think I would prefer this, too. Also, the cards are really not that beautiful right now and we need to integrate the pre-loading functionality of the DriveDetailPage so I think that's a new user story right there :D For now, this is fine right?

Yes i like the idea of a new Userstory, i think for now the cards are fine, if we think of them as placeholders.

2022-12-07 21:20 UTC, fynsta requested changes

2022-12-07 21:25 UTC, istzen commented on lib/util/trip/drive_card.dart
> +                    indicator: OutlinedDotIndicator(),
yes I will do that

2022-12-07 21:28 UTC, istzen commented on lib/util/trip/trip_page_builder.dart
> +                  //we could change this to trip.starttime the question is what we are doing with
yes i think this comment can be deleted

2022-12-10 12:21 UTC, istzen commented on lib/drives/pages/drives_page.dart
> +    //todo: method to get userId
yes, thanks for the reminder

2022-12-10 12:23 UTC, istzen commented on lib/util/trip/trip_page_builder.dart
> +              emptyMessage: 'No upcoming $name',
so what do you suggest?

2022-12-10 12:58 UTC, fynsta commented on lib/util/trip/trip_page_builder.dart
> +              emptyMessage: 'No upcoming $name',
I don't see a better way either, so we can leave it like this... the person who adds localization will have to think about this lol

2022-12-11 09:48 UTC, fynsta commented
you wanted to revert the ios files, not the macos ones 🤣

2022-12-11 09:52 UTC, istzen commented
> you wanted to revert the ios files, not the macos ones 🤣

yes, i did revert the ios files the descriotion of the commit is just wrong i'm sorry

2022-12-11 13:35 UTC, fynsta approved these changes

2022-12-11 13:42 UTC, merged