Change BirthDate to Age
MOTIS-Mitfahr-App/flutter-app pull request #68
Opened 2023-01-19 16:09 UTC by fynsta

As discussed in the AG meeting. Also fixes the initial date on the datePicker to be the currently selected date.

2023-01-19 17:31 UTC, Eddie-42 approved these changes

2023-01-20 10:40 UTC, Showcas approved these changes

2023-01-21 13:50 UTC, MarkFalke requested changes

2023-01-21 14:10 UTC, fynsta commented on lib/account/pages/profile_page.dart
> +            (DateTime.now().difference(_profile!.birthDate!).inDays ~/ 365).toString(),
I think I found a nice solution that does not even require us to think about leap years. Can you verify? :)

2023-01-21 17:26 UTC, MarkFalke approved these changes

2023-01-21 17:40 UTC, merged